### ISSUE TITLE
檔案的命名

### ISSUE THREAD

**Issue by Jeeying** [Ray625/beitou#6]
https://github.com/Ray625/beitou/blob/b39062579e7ee195f3347be0525fceed715ade4c/src/components/Q%26A/Q%26A.jsx#L43

檔案的命名盡量少用特殊符號哦

**Comment by Jeeying** [comment]
activity book.pdf
也建議盡量不要有空白哦

**Comment by Ray625** [comment]
收到，去查了一下關於這個問題，是因為在不同作業系統或文件系統下，對空白及特殊符號的編碼可能會不同，不使用可以避免不必要的錯誤。大多使用英文、底線_或是短橫-命名。

**Comment by Jeeying** [comment]
我記得推薦的那個空白套件，也可以幫你抓系統的空白，尤其同windows的人協做，常在幫刪除奇怪空白，哈
