### ISSUE TITLE
圖片的使用

### ISSUE THREAD

**Issue by Jeeying** [Ray625/beitou#8]
https://github.com/Ray625/beitou/blob/b39062579e7ee195f3347be0525fceed715ade4c/src/components/Ui/titleGroup.jsx#L16

一般如果這張圖片不需要頻繁更替，確實會常放在public，因為不會經過打包，但如果像是產品圖，容易替換的，我們通常不會想新增圖片還要去改程式，所以檔名會相同覆蓋，但如果放在public的話，會因為快取導致使用者無法馬上看到新的圖片
可以改用編譯過的圖片
```
import img from "assets/img.png"
```

**Comment by Ray625** [comment]
那這邊這種標題、不太會更動的圖檔，是應該放在public中，還是要讓他被打包呢，打包是會讓檔案壓縮，執行的時候速度更快嗎?

像是做了loading頁是因為網頁一開啟首頁的圖片會需要時間加載，會有空白的畫面，是不是有什麼方法可以讓加載圖片的速度快一點

**Comment by Jeeying** [comment]
我猜應該有打包的時候在壓縮圖片的工具，但實務上沒這樣做，一個是你不確定工具壓縮的圖片會不會讓圖片壞掉，比如調色或模糊
過打包會有hash檔檔名後面，避免快取，就像你使用css module一樣，後面會加一串文字
一般要讓圖片變快無非就變小或是放cdn，或是svg，尤其手機不要用桌機的圖片，會快很多
